### ISSUE TITLE
adding of multiple AROS for each role a user has

### ISSUE THREAD

**Issue by sebbZA** [FriendsOfCake/Authorize#3]
there is no functionality which adds multiple aros in the parentNode function in the User Model?

public function parentNode() {
            $u = $this->read();
                return array('Role' => array('id' => 1), array('id' => 2));
        }

This example does not work

**Comment by ceeram** [comment]
Your parentNode() should return null, or primary role, not all, the habtm acl handles that already to find all associated roles:

https://github.com/ceeram/Authorize/blob/master/Controller/Component/Acl/HabtmDbAcl.php#L31-L35
